export default {
  dateFilter: {
    anytime: "상관없음",
    today: "오늘",
    tomorrow: "내일",
    thisWeek: "이번주",
    nextWeek: "다음주",
    thisMonth: "이번달",
  },
  regionFilter: {
    anywhere: "상관없음",
    seoul: "서울",
    busan: "부산",
    daegu: "대구",
    incheon: "인천",
    gwangju: "광주",
    daejeon: "대전",
    ulsan: "울산",
    jeju: "제주",
    gyeonggi: "경기",
    gangwon: "강원",
    chungcheon: "충청",
    jeolla: "전라",
    gyeongsang: "경상",
  },
  groupFilter: {
    anygroup: "상관없음",
    small: "소그룹(5명 이하)",
    medium: "중그룹(5~20명)",
    large: "대그룹(20명 이상)",
  },
};
